//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_CONGVIEC
    {
        public int MACV { get; set; }
        public string MAMH { get; set; }
        public int MANV { get; set; }
        public int MATUAN { get; set; }
        public string TENCONGVIEC { get; set; }
        public Nullable<int> MAMODULE { get; set; }
        public string Nguồn_gốc { get; set; }
        public string TRANGTHAI { get; set; }
        public string GHICHU { get; set; }
    
        public virtual DUAN DUAN { get; set; }
        public virtual MODULE MODULE { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual TUAN TUAN { get; set; }
    }
}
