//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUAN()
        {
            this.QL_CONGVIEC = new HashSet<QL_CONGVIEC>();
        }
    
        public int MATUAN { get; set; }
        public Nullable<int> GIATRI { get; set; }
        public Nullable<int> STTTUAN { get; set; }
        public string TENTUAN { get; set; }
        public Nullable<System.DateTime> TUNGAY { get; set; }
        public Nullable<System.DateTime> DENNGAY { get; set; }
        public Nullable<int> SOGIOLAM { get; set; }
        public Nullable<bool> TINHTRANG { get; set; }
        public Nullable<int> Nam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QL_CONGVIEC> QL_CONGVIEC { get; set; }
        public virtual THANG THANG { get; set; }
    }
}
